In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv("C:\\unikaksha\\datascience\\project_DS\\miniProject2\\emails.csv")

In [3]:
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [4]:
data.shape

(5172, 3002)

### data preprocessing 

In [5]:
sum(data.isnull().sum())

0

In [6]:
data.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [7]:
data.isnull().any()

Email No.     False
the           False
to            False
ect           False
and           False
              ...  
military      False
allowing      False
ff            False
dry           False
Prediction    False
Length: 3002, dtype: bool

In [8]:
data.columns[data.isnull().any()].tolist()

[]

In [9]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier


### train and test data spliting

In [10]:
X=data.iloc[:,1:3001]
Y=data.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.25)

### Naive bayes algorithm

In [11]:
NB=MultinomialNB()
NB.fit(x_train,y_train)

MultinomialNB()

In [12]:
y_act=y_test
y_pred=NB.predict(x_test)

In [13]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
NB_accuracy=accuracy_score(y_act,y_pred)
print(NB_accuracy)

              precision    recall  f1-score   support

           0       0.98      0.96      0.97       900
           1       0.91      0.95      0.93       393

    accuracy                           0.95      1293
   macro avg       0.94      0.95      0.95      1293
weighted avg       0.96      0.95      0.95      1293

[[861  39]
 [ 20 373]]
0.954369682907966


### SVM algorithm

In [14]:
svm=SVC(kernel="linear")
svm.fit(x_train,y_train)

SVC(kernel='linear')

In [15]:
y_act=y_test
y_pred=svm.predict(x_test)

In [16]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
svm_accuracy=accuracy_score(y_act,y_pred)
print(svm_accuracy)

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       900
           1       0.94      0.94      0.94       393

    accuracy                           0.96      1293
   macro avg       0.96      0.96      0.96      1293
weighted avg       0.96      0.96      0.96      1293

[[877  23]
 [ 23 370]]
0.9644238205723125


### Decision tree algorithm

In [17]:
DT=DecisionTreeClassifier()
DT.fit(x_train,y_train)

DecisionTreeClassifier()

In [18]:
y_act=y_test
y_pred=DT.predict(x_test)

In [19]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
DT_accuracy=accuracy_score(y_act,y_pred)
print(DT_accuracy)

              precision    recall  f1-score   support

           0       0.95      0.95      0.95       900
           1       0.89      0.89      0.89       393

    accuracy                           0.93      1293
   macro avg       0.92      0.92      0.92      1293
weighted avg       0.93      0.93      0.93      1293

[[859  41]
 [ 44 349]]
0.934261407579273


### Random forest algorithm

In [20]:
RF=RandomForestClassifier()
RF.fit(x_train,y_train)

RandomForestClassifier()

In [21]:
y_act=y_test
y_pred=RF.predict(x_test)

In [22]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
RF_accuracy=accuracy_score(y_act,y_pred)
print(RF_accuracy)

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       900
           1       0.98      0.93      0.95       393

    accuracy                           0.97      1293
   macro avg       0.97      0.96      0.97      1293
weighted avg       0.97      0.97      0.97      1293

[[891   9]
 [ 26 367]]
0.9729311678267595


### Bagging Classifier algorithm

In [23]:
BG=BaggingClassifier()
BG.fit(x_train,y_train)

BaggingClassifier()

In [24]:
y_act=y_test
y_pred=BG.predict(x_test)

In [25]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
BG_accuracy=accuracy_score(y_act,y_pred)
print(BG_accuracy)

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       900
           1       0.95      0.91      0.93       393

    accuracy                           0.96      1293
   macro avg       0.95      0.94      0.95      1293
weighted avg       0.96      0.96      0.96      1293

[[880  20]
 [ 35 358]]
0.9574632637277649


### accuracy score

In [26]:
print("Naive Bayes accuracy score: ",NB_accuracy)
print("SVC accuracy score: ",svm_accuracy)
print("Decision Tree accuracy score: ",DT_accuracy)
print("Random Forest accuracy score: ",RF_accuracy)
print("Bagging accuracy score: ",BG_accuracy)

Naive Bayes accuracy score:  0.954369682907966
SVC accuracy score:  0.9644238205723125
Decision Tree accuracy score:  0.934261407579273
Random Forest accuracy score:  0.9729311678267595
Bagging accuracy score:  0.9574632637277649
