In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
data=pd.read_csv("C:\\unikaksha\\datascience\\project_DS\\miniProject13\\emails.csv")

In [5]:
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [6]:
data.shape

(5172, 3002)

### data preprocessing 

In [7]:
sum(data.isnull().sum())

0

In [8]:
data.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [9]:
data.isnull().any()

Email No.     False
the           False
to            False
ect           False
and           False
              ...  
military      False
allowing      False
ff            False
dry           False
Prediction    False
Length: 3002, dtype: bool

In [10]:
data.columns[data.isnull().any()].tolist()

[]

In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier


### train and test data spliting

In [12]:
X=data.iloc[:,1:3001]
Y=data.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.25)

### Naive bayes algorithm

In [13]:
NB=MultinomialNB()
NB.fit(x_train,y_train)

MultinomialNB()

In [14]:
y_act=y_test
y_pred=NB.predict(x_test)

In [15]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
NB_accuracy=accuracy_score(y_act,y_pred)
print(NB_accuracy)

              precision    recall  f1-score   support

           0       0.98      0.95      0.96       917
           1       0.88      0.94      0.91       376

    accuracy                           0.95      1293
   macro avg       0.93      0.94      0.93      1293
weighted avg       0.95      0.95      0.95      1293

[[868  49]
 [ 22 354]]
0.9450889404485692


### SVM algorithm

In [16]:
svm=SVC(kernel="linear")
svm.fit(x_train,y_train)

SVC(kernel='linear')

In [17]:
y_act=y_test
y_pred=svm.predict(x_test)

In [18]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
svm_accuracy=accuracy_score(y_act,y_pred)
print(svm_accuracy)

              precision    recall  f1-score   support

           0       0.98      0.97      0.98       917
           1       0.93      0.95      0.94       376

    accuracy                           0.97      1293
   macro avg       0.96      0.96      0.96      1293
weighted avg       0.97      0.97      0.97      1293

[[892  25]
 [ 19 357]]
0.9659706109822119


### Decision tree algorithm

In [19]:
DT=DecisionTreeClassifier()
DT.fit(x_train,y_train)

DecisionTreeClassifier()

In [20]:
y_act=y_test
y_pred=DT.predict(x_test)

In [21]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
DT_accuracy=accuracy_score(y_act,y_pred)
print(DT_accuracy)

              precision    recall  f1-score   support

           0       0.95      0.96      0.95       917
           1       0.90      0.87      0.88       376

    accuracy                           0.93      1293
   macro avg       0.92      0.91      0.92      1293
weighted avg       0.93      0.93      0.93      1293

[[879  38]
 [ 50 326]]
0.9319412219644239


### Random forest algorithm

In [22]:
RF=RandomForestClassifier()
RF.fit(x_train,y_train)

RandomForestClassifier()

In [23]:
y_act=y_test
y_pred=RF.predict(x_test)

In [24]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
RF_accuracy=accuracy_score(y_act,y_pred)
print(RF_accuracy)

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       917
           1       0.96      0.94      0.95       376

    accuracy                           0.97      1293
   macro avg       0.97      0.96      0.97      1293
weighted avg       0.97      0.97      0.97      1293

[[904  13]
 [ 24 352]]
0.97138437741686


### Bagging Classifier algorithm

In [28]:
tree=DecisionTreeClassifier()
BG=BaggingClassifier(tree, n_estimators=100, max_samples=0.8,
                        random_state=1)
BG.fit(x_train,y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, random_state=1)

In [29]:
y_act=y_test
y_pred=BG.predict(x_test)

In [30]:
print(classification_report(y_act,y_pred))
print(confusion_matrix(y_act,y_pred))
BG_accuracy=accuracy_score(y_act,y_pred)
print(BG_accuracy)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       917
           1       0.95      0.95      0.95       376

    accuracy                           0.97      1293
   macro avg       0.96      0.96      0.96      1293
weighted avg       0.97      0.97      0.97      1293

[[897  20]
 [ 19 357]]
0.9698375870069605


### accuracy score

In [31]:
print("Naive Bayes accuracy score: ",NB_accuracy)
print("SVC accuracy score: ",svm_accuracy)
print("Decision Tree accuracy score: ",DT_accuracy)
print("Random Forest accuracy score: ",RF_accuracy)
print("Bagging accuracy score: ",BG_accuracy)

Naive Bayes accuracy score:  0.9450889404485692
SVC accuracy score:  0.9659706109822119
Decision Tree accuracy score:  0.9319412219644239
Random Forest accuracy score:  0.97138437741686
Bagging accuracy score:  0.9698375870069605


In [35]:
dt = DecisionTreeClassifier(max_features=1.0,splitter='random', max_depth=210)
dt.fit(x_train, y_train)
y_pred4 = dt.predict(x_test)
print('Accuracy score of Decision Tree:', accuracy_score(y_act, y_pred4))

Accuracy score of Decision Tree: 0.9319412219644239


In [41]:
rfc = RandomForestClassifier(n_estimators=200,criterion='log_loss',max_samples=.9) #criterion{“gini”, “entropy”, “log_loss”}
rfc.fit(x_train,y_train)
y_pred3 = rfc.predict(x_test)
print("Accuracy Score of Random Forest Classifier : ", accuracy_score(y_pred3,y_act))

Accuracy Score of Random Forest Classifier :  0.9783449342614076


In [43]:
from sklearn.ensemble import BaggingClassifier
Naivebag = BaggingClassifier(NB, n_estimators=100, max_samples=1.0,
random_state=1)
Naivebag.fit(x_train, y_train)

Svmbag = BaggingClassifier(svm, n_estimators=100, max_samples=1.0,
random_state=1)
Svmbag.fit(x_train, y_train)

Decisionbag = BaggingClassifier(DT, n_estimators=100, max_samples=1.0,
random_state=1)
Decisionbag.fit(x_train, y_train)

RandomBag = BaggingClassifier(RF, n_estimators=100, max_samples=1.0,
random_state=1)
RandomBag.fit(x_train, y_train)

bag1 = Naivebag.predict(x_test)
print("AS - Bagged Naive",bag1)
bag2 = Svmbag.predict(x_test)
print("AS - Bagged SVM",bag2)
bag3 = Decisionbag.predict(x_test)
print("AS - Bagged DecisionTree",bag3)
bag4 = RandomBag.predict(x_test)
print("AS - Bagged Random Forest",bag4)

KeyboardInterrupt: 

In [44]:
Naivebag = BaggingClassifier(NB, n_estimators=100, max_samples=1.0,
random_state=1)
Naivebag.fit(x_train, y_train)
bag1 = Naivebag.predict(x_test)
print("AS - Bagged Naive",accuracy_score(y_act,bag1))

AS - Bagged Naive 0.9466357308584686


In [48]:
Svmbag = BaggingClassifier(svm, n_estimators=100, max_samples=1.0,
random_state=1)
Svmbag.fit(x_train, y_train)
bag2 = Svmbag.predict(x_test)
print("AS - Bagged SVM",accuracy_score(y_act,bag2))

AS - Bagged SVM 0.9644238205723125


In [46]:
Decisionbag = BaggingClassifier(DT, n_estimators=100, max_samples=1.0,
random_state=1)
Decisionbag.fit(x_train, y_train)
bag3 = Decisionbag.predict(x_test)
print("AS - Bagged DecisionTree",accuracy_score(y_act,bag3))

AS - Bagged DecisionTree 0.9721577726218097


In [47]:
RandomBag = BaggingClassifier(RF, n_estimators=100, max_samples=1.0,
random_state=1)
RandomBag.fit(x_train, y_train)
bag4 = RandomBag.predict(x_test)
print("AS - Bagged Random Forest",accuracy_score(y_act,bag4))

AS - Bagged Random Forest 0.974477958236659
